version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run: python test.py
  deploy:
    docker:
      - image: cimg/python:3.9
    steps:   
      - checkout
      - run: echo "Deploying to dev server"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
                only: dev
          
    
